(* ::Package:: *)

(* ::Input:: *)
(*(* ====================================================*)(*HAA ALGORITHM FOR Fine-structure constant*)(*With LogGamma stabilization and pure real output*)(* ====================================================*)ClearAll["Global`*"];*)
(*DownValues[KappaStabilized]={};*)
(**)
(*(*Stabilized Kappa function with LogGamma*)*)
(*KappaStabilized[q_Integer]:=KappaStabilized[q]=Module[{omega,logSum,prec=300},omega=Exp[2*Pi*I/q];*)
(*logSum=Sum[LogGamma[3/2-omega^j/2],{j,1,q-1}];*)
(*SetPrecision[(2^q)/(Pi^(q/2))*Exp[logSum]-1,prec]];*)
(**)
(*(*Main algorithm-completely isolated*)*)
(*Algorithm2RestartOptimizedV3[C_,S0initial_,epsMax_,maxRestarts_,maxQ_]:=Module[{Cscalar=SetPrecision[C,300],S0=SetPrecision[S0initial,300],A,q,totalCorrections={},restartCount=0,kappa,currAbsErr,resultList={},finalA,epsAbs,errorAbs,errorRel,dominantDesc,m1,binaryCode,posCount,negCount,haaString},(*Internal greedy function*)GreedyPass[Astart_,qStart_]:=Module[{localA=Astart,localQ=qStart,localCorrections={},localImproved,localkappa,localError},While[localQ<=maxQ,localImproved=True;*)
(*While[localImproved,localImproved=False;*)
(*localkappa=KappaStabilized[localQ];*)
(*(*Test both directions*)If[Abs[Re[localA+localkappa]-Cscalar]<Abs[Re[localA]-Cscalar],localA=localA+localkappa;*)
(*AppendTo[localCorrections,{localQ,+1}];*)
(*localImproved=True,If[Abs[Re[localA-localkappa]-Cscalar]<Abs[Re[localA]-Cscalar],localA=localA-localkappa;*)
(*AppendTo[localCorrections,{localQ,-1}];*)
(*localImproved=True]];];*)
(*localQ++;*)
(*(*Stopping check*)If[Abs[(Re[localA]-Cscalar)/Cscalar]<=epsMax,Break[]];];*)
(*Return[{localA,localCorrections}];];*)
(*(*Main loop with restarts*)Print["===================================================="];*)
(*Print["HAA ALGORITHM: LogGamma Stabilization"];*)
(*Print["Target: C = ",ScientificForm[Cscalar,5]];*)
(*Print["Initial S0 = ",S0];*)
(*Print["Tolerance: epsilon_rel = ",epsMax];*)
(*epsAbs=epsMax*Abs[Cscalar];*)
(*Print["           epsilon_abs = ",ScientificForm[epsAbs,3]];*)
(*Print["Maximum q: ",maxQ,", Maximum restarts: ",maxRestarts];*)
(*Print["===================================================="];*)
(*While[restartCount<maxRestarts&&Abs[(S0-Cscalar)/Cscalar]>epsMax,restartCount++;*)
(*Print["\n*** RESTART ",restartCount," ***"];*)
(*Print["New S0 = ",Re[S0]];*)
(*Print["Current abs. error: ",ScientificForm[Abs[Re[S0]-Cscalar],5]];*)
(*Print["Current rel. error: ",ScientificForm[Abs[(Re[S0]-Cscalar)/Cscalar],5]];*)
(*(*Adaptive start q*)currAbsErr=Abs[Re[S0]-Cscalar];*)
(*q=2;*)
(*While[q<maxQ&&Abs[KappaStabilized[q]]>currAbsErr,q++];*)
(*Print["  Starting from q = ",q," (|kappa_q| ~~ ",ScientificForm[Abs[KappaStabilized[q]],3],")"];*)
(*(*Greedy pass*){A,resultList}=GreedyPass[S0,q];*)
(*(*Display results*)Print["Restart ",restartCount," completed."];*)
(*Print["Number of corrections in this restart: ",Length[resultList]];*)
(*totalCorrections=Join[totalCorrections,resultList];*)
(*Print["Cumulative corrections: ",Length[totalCorrections]];*)
(*Print["Current rel. error: ",ScientificForm[Abs[(Re[A]-Cscalar)/Cscalar],10]];*)
(*(*Prepare for next restart*)S0=A;];*)
(*(*Final results*)finalA=Re[A];*)
(*Print["\n",StringRepeat["=",60]];*)
(*Print["FINAL RESULTS OF HAA ALGORITHM"];*)
(*Print[StringRepeat["=",60]];*)
(*Print["Number of restarts: ",restartCount];*)
(*Print["Total corrections: ",Length[totalCorrections]];*)
(*Print["Final S0: ",ScientificForm[finalA,40]];*)
(*Print["Target C: ",ScientificForm[Cscalar,40]];*)
(*(*Errors*)errorAbs=Abs[finalA-Cscalar];*)
(*errorRel=errorAbs/Abs[Cscalar];*)
(*Print["\nERRORS:"];*)
(*Print["Absolute: Delta = ",ScientificForm[errorAbs,10]];*)
(*Print["Relative: delta = ",ScientificForm[errorRel,10]];*)
(*Print["Number of accurate decimals: ~",-Floor[Log10[errorAbs]]];*)
(*(*Hierarchical structure analysis*)If[Length[totalCorrections]>0,Print["\nHIERARCHICAL STRUCTURE OF alpha^{-1}:"];*)
(*(*Dominant descriptor*)dominantDesc=First[totalCorrections];*)
(*m1=Length[Cases[totalCorrections,{dominantDesc[[1]],_}]];*)
(*Print["  Dominant descriptor: q* = ",dominantDesc[[1]],", m* = ",m1,", sign = ",If[dominantDesc[[2]]==1,"+1","-1"]];*)
(*(*Precise binary code*)binaryCode=Rest[totalCorrections];*)
(*posCount=Count[binaryCode,{_,1}];*)
(*negCount=Count[binaryCode,{_,-1}];*)
(*Print["  Precise binary code: ",Length[binaryCode]," corrections"];*)
(*Print["    (+1: ",posCount,", -1: ",negCount,")"];*)
(*(*Hierarchical list*)Print["\nHIERARCHICAL LIST (q, c):"];*)
(*For[i=1,i<=Length[totalCorrections],i++,Print["  ",i,". (",totalCorrections[[i,1]],", ",If[totalCorrections[[i,2]]==1,"+1","-1"],")"];];*)
(*(*Export HAA code*)haaString=StringJoin[Riffle[Map[ToString,totalCorrections,{2}],", "]];*)
(*Export["alpha_inverse_HAA_code_V3.txt",{"alpha^{-1} HAA Code (V3):",haaString,"","Relative error: "<>ToString[ScientificForm[errorRel,5]],"Absolute error: "<>ToString[ScientificForm[errorAbs,5]],"Number of corrections: "<>ToString[Length[totalCorrections]],"q range: "<>ToString[Min[totalCorrections[[All,1]]]]<>" -> "<>ToString[Max[totalCorrections[[All,1]]]]},"Text"];*)
(*Print["\n HAA code saved in 'alpha_inverse_HAA_code_V3.txt'"];];*)
(*Return[{finalA,totalCorrections,restartCount}];];*)
(**)
(*(* ====================================================*)*)
(*(*RUNNING ON Fine-structure constant alpha^{-1}*)*)
(*(* ====================================================*)*)
(**)
(*Print["\n",StringRepeat["#",80]];*)
(*Print["TEST FINE-STRUCTURE CONSTANT alpha^{-1} - HAA ALGORITHM"];*)
(*Print[StringRepeat["#",80]];*)
(**)
(*(*Parameters for alpha^{-1}*)*)
(*alphaInverse=137.035999177;(*CODATA 2022 value*)S0initial=137;(*Floor[alphaInverse]=137*)epsTarget=9.99*10^-17;*)
(*maxRestarts=30;*)
(*maxQ=80;*)
(**)
(*Print["\nPARAMETERS:"];*)
(*Print["  alpha^{-1} (target) = ",ScientificForm[alphaInverse,10]];*)
(*Print["  S0initial = ",S0initial];*)
(*Print["  epsilon_target = ",epsTarget];*)
(*Print["  maxRestarts = ",maxRestarts];*)
(*Print["  maxQ = ",maxQ];*)
(**)
(*(*Execution*)*)
(*Print["\nStarting HAA ALGORITHM ..."];*)
(*result=Algorithm2RestartOptimizedV3[alphaInverse,S0initial,epsTarget,maxRestarts,maxQ];*)
(**)
(*(*Verification*)*)
(*If[result!=$Failed&&Length[result]==3,{Afinal,corrections,restarts}=result;*)
(*Print["\n",StringRepeat["=",80]];*)
(*Print["REPRODUCIBILITY VERIFICATION:"];*)
(*(*Test 1:Coefficient verification*)allBinary=AllTrue[corrections,MemberQ[{1,-1},#[[2]]]&];*)
(*Print["   All coefficients are +-1: ",allBinary];*)
(*(*Test 2:Dominant descriptor verification*)If[Length[corrections]>0,dominantQ=corrections[[1,1]];*)
(*multiplicity=Length[Cases[corrections,{dominantQ,_}]];*)
(*Print["   Dominant descriptor: q* = ",dominantQ,", m* = ",multiplicity],Print["   No corrections - empty hierarchical code"]];*)
(*(*Test 3:Accuracy verification*)finalError=Abs[(Afinal-SetPrecision[alphaInverse,300])/SetPrecision[alphaInverse,300]];*)
(*Print["   Relative error: ",ScientificForm[finalError,5]];*)
(*Print["   Status: ",If[finalError<epsTarget,"BELOW TARGET","CLOSE TO TARGET"]];*)
(*(*Final HAA formula*)Print["\n",StringRepeat["=",80]];*)
(*Print["FINAL HAA FORMULA FOR alpha^{-1}:"];*)
(*If[Length[corrections]>0,formula="alpha^{-1} ~~ S0 + ";*)
(*For[i=1,i<=Length[corrections],i++,If[i==1,formula=formula<>ToString[multiplicity]<>"*kappa_"<>ToString[dominantQ],{q,c}=corrections[[i]];*)
(*formula=formula<>If[c==1," + kappa_"," - kappa_"]<>ToString[q]];];*)
(*formula=formula<>" + ...";*)
(*Print["  ",formula],Print["  alpha^{-1} ~~ S0 = ",S0initial]];*)
(*Print["\n",StringRepeat["#",80]];*)
(*Print[" ALGORITHM SUCCESSFULLY COMPLETED"];*)
(*Print[StringRepeat["#",80]],Print["\n Execution error! Result: ",result];];*)



